show databases;
create database grocery_app;
use grocery_app;
create table grocery(
name varchar(255),
category varchar(255),
price  int );
insert into grocery values("Apple","Fruits",10);
insert into grocery values("orange","Fruits",12);
insert into grocery values("Grapes","Fruits",15);
insert into grocery values("Banana","Fruits",6);
insert into grocery values("Watermelon","Fruits",30);
insert into grocery values("PineApple","Fruits",40);
insert into grocery values("potato","Vegetable",10);
insert into grocery values("Tomato","Vegetable",5);
insert into grocery values("Onion","Vegetable",6);
insert into grocery values("Carrot","Vegetable",8);
insert into grocery values("Beetroot","Vegetable",10);
insert into grocery values("Broccoli","Vegetable",12);
insert into grocery values("Almonds","Nuts",4);
insert into grocery values("Walnuts","Nuts",5);
insert into grocery values("Pecans","Nuts",3);
insert into grocery values("Cashews","Nuts",8);
insert into grocery values("Hazelnuts","Nuts",10);
insert into grocery values("Peanuts","Nuts",3);
insert into grocery values("Notebooks","Stationery",50);
insert into grocery values("Diaries","Stationery",200);
insert into grocery values("Pen","Stationery",20);
insert into grocery values("Pencils","Stationery",5);
insert into grocery values("Calculator","Stationery",500);
insert into grocery values("Punching Machine","Stationery",600);
insert into grocery values("Coca-Cola","Drinks",25);
insert into grocery values("Pepsi","Drinks",30);
insert into grocery values("Limca","Drinks",15);
insert into grocery values("Sprite","Drinks",35);
insert into grocery values("Fanta","Drinks",25);
insert into grocery values("Appy Fizz","Drinks",30);
insert into grocery values("Wheat","Grains",50);
insert into grocery values("Oats","Grains",50);
insert into grocery values("Rice","Grains",60);
insert into grocery values("Corn","Grains",20);
insert into grocery values("Barley","Grains",30);
insert into grocery values("Sorghum","Grains",30);
insert into grocery values("Millet","Grains",25);
select * from grocery;
alter table grocery add discount double;
update grocery set discount=10;